name: Generate Changelog

on:
  push:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: true
          breaking-labels: 'breaking,breaking-change'
          bug-labels: 'bug,fix'
          enhancement-labels: 'enhancement,feature'
          issues: true
          pulls: true
          issues-wo-labels: true
          pr-wo-labels: true
          unreleased: true
          unreleased-label: 'Upcoming'
          since-tag: ''
          output: 'CHANGELOG.md'
          base: 'HISTORY.md'

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs: update changelog" || echo "No changes to commit"
          git push
