# 项目名
name: Generate
on:
  push:
    branches:
      - main
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write # Add explicit permissions

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: true
          breaking-labels: 'breaking,breaking-change'
          bug-labels: 'bug,fix'
          enhancement-labels: 'enhancement,feature'
          issues: true
          pulls: true
          issues-wo-labels: true
          pr-wo-labels: true
          unreleased: true
          unreleased-label: 'Upcoming'
          since-tag: ''
          output: 'CHANGELOG.md'
          base: 'HISTORY.md'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update changelog"
          file_pattern: "CHANGELOG.md"
